### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory

### ISSUE THREAD

**Issue by luyaozhi** [pengfeidip/refindeDet_Pytorch#2]
when i test with csv_eval.py ,i found that 
-------------------------------------------------------------------------------------
Finished loading model!
100%|████████████████████████████████████████████████████████████████████████████| 4952/4952 [28:41<00:00,  2.80it/s]
Evaluating detections
Computing the mAp ing...... please wait a moment
{'aeroplane': 0.4118960533629764}  1.3266966342926025
{'bicycle': 0.5911391187797893}  0.38912224769592285
{'bird': 0.42551310936158354}  2.3506739139556885
{'boat': 0.23346355591307988}  0.6136162281036377
{'bottle': 0.3144579245285554}  0.7234435081481934
{'bus': 0.6386174383488569}  0.19341397285461426
{'car': 0.6428438560529188}  2.6013054847717285
{'cat': 0.6638138267126951}  1.782047986984253
{'chair': 0.3327659564939412}  1.982759952545166
{'cow': 0.4983186044476249}  0.153639554977417
{'diningtable': 0.31075073778629303}  0.23151183128356934
{'dog': 0.671084772456776}  1.8593437671661377
{'horse': 0.7722394710237329}  0.3605620861053467
{'motorbike': 0.765714087269523}  0.2247474193572998
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/generated/../generic/THCTensorMathPointwise.cu line=308 error=2 : out of memory
Traceback (most recent call last):
  File "/data/niu/refindeDet_Peng/mAP.py", line 118, in single_class_ap
    iou = self.compute_iou(preds_coords, gts_coords).cpu()
  File "/data/niu/refindeDet_Peng/mAP.py", line 195, in compute_iou
    box2[:, 2:].unsqueeze(0).expand(N, M, 2),  # [M,2] -> [1,M,2] -> [N,M,2]
RuntimeError: CUDA error: out of memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "csv_eval.py", line 191, in <module>
    test_net(net,  dataset, gt_file)
  File "csv_eval.py", line 152, in test_net
    evaluate_detections(predictions, dataset, gt_file)
  File "csv_eval.py", line 164, in evaluate_detections
    mAP, ap_list = ap()
  File "/data/niu/refindeDet_Peng/mAP.py", line 49, in __call__
    self.class_list)
  File "/data/niu/refindeDet_Peng/mAP.py", line 70, in compute_map
    ap = self.single_class_ap(preds, labels, class_name, iou_thresh)
  File "/data/niu/refindeDet_Peng/mAP.py", line 125, in single_class_ap
    iou_temp = self.compute_iou(preds_coords[idx:idx+gap, :], gts_coords).cpu()
  File "/data/niu/refindeDet_Peng/mAP.py", line 199, in compute_iou
    wh = rb - lt  # [N,M,2]
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/generated/../generic/THCTensorMathPointwise.cu:308

Can you help me with it? thank you very much ~~

**Comment by pengfeidip** [comment]
`box2[:, 2:].unsqueeze(0).expand(N, M, 2), # [M,2] -> [1,M,2] -> [N,M,2]` 

从这来看，是因为在计算IOU的时候，我用“空间”换“时间”的时候占用过多的显存。估计是预测出来的box太多了，可以提高阈值减少预测出来的box，但是这样会对mAP指标有点影响。或者，你计算IOU的时候**分批计算**。其实我后来也改为了分批计算IOU，但是没有更新上去。

**Comment by luyaozhi** [comment]
> `box2[:, 2:].unsqueeze(0).expand(N, M, 2), # [M,2] -> [1,M,2] -> [N,M,2]`
> 
> 从这来看，是因为在计算IOU的时候，我用“空间”换“时间”的时候占用过多的显存。估计是预测出来的box太多了，可以提高阈值减少预测出来的box，但是这样会对mAP指标有点影响。或者，你计算IOU的时候**分批计算**。其实我后来也改为了分批计算IOU，但是没有更新上去。

请问您有更新分批计算IOU的打算吗？

**Comment by pengfeidip** [comment]
@luyaozhi  抱歉，短期没有，因为这个工程的电脑目前不在我手上。

**Comment by luyaozhi** [comment]
谢谢
