### ISSUE TITLE
关于mixup实现

### ISSUE THREAD

**Issue by songwsx** [pengfeidip/refindeDet_Pytorch#3]
我对您的这两个实现很感兴趣，请问可以开源出来吗？非常感谢您的代码，写得简洁易懂。
```
Mixed precision training with apex
Mixup data augmentation with β(1.5, 1.5)
```

**Comment by pengfeidip** [comment]
## Mixup data augmentation
mixup的具体内容
https://github.com/pengfeidip/refindeDet_Pytorch/blob/743a6ffdfc6efeef7bce5ce9fb4adb5211b7635f/train_refinedet.py#L304

mixup后的loss计算方式
https://github.com/pengfeidip/refindeDet_Pytorch/blob/743a6ffdfc6efeef7bce5ce9fb4adb5211b7635f/train_refinedet.py#L316

----
## Mixed precision training with apex


模型半精度优化
https://github.com/pengfeidip/refindeDet_Pytorch/blob/743a6ffdfc6efeef7bce5ce9fb4adb5211b7635f/train_refinedet.py#L184
loss半精度优化
https://github.com/pengfeidip/refindeDet_Pytorch/blob/743a6ffdfc6efeef7bce5ce9fb4adb5211b7635f/train_refinedet.py#L243

半精度就多了几行代码，看看`apex`的文档就知道了

**Comment by songwsx** [comment]
非常感谢您的帮助
